// src/lib/3mf-export.ts
// 3MF export utilities for the Manifold API

import type { ManifoldType } from './manifold';
import { fileForContentTypes, FileForRelThumbnail, to3dmodel } from '@jscadui/3mf-export';
import { strToU8, Zippable, zipSync } from 'fflate';

/**
 * 3MF mesh data structure
 */
interface Mesh3MF {
  id: string;
  vertices: Float32Array;
  indices: Uint32Array;
  name?: string;
}

/**
 * 3MF child component reference
 */
interface Child3MF {
  objectID: string;
  transform?: number[]; // 4x4 matrix as flat array
}

/**
 * 3MF component definition
 */
interface Component3MF {
  id: string;
  children: Array<Child3MF>;
  name?: string;
}

/**
 * 3MF header metadata
 */
interface Header3MF {
  unit?: 'micron' | 'millimeter' | 'centimeter' | 'inch' | 'foot' | 'meter';
  title?: string;
  author?: string;
  description?: string;
  application?: string;
  creationDate?: string;
  license?: string;
  modificationDate?: string;
}

/**
 * Complete 3MF data structure
 */
interface To3MF {
  meshes: Array<Mesh3MF>;
  components: Array<Component3MF>;
  items: Array<Child3MF>;
  precision: number;
  header: Header3MF;
}

/**
 * 3MF export options
 */
export interface Export3MFOptions {
  filename?: string;
  precision?: number;
  header?: Partial<Header3MF>;
}

/**
 * Convert a Manifold mesh to 3MF format blob
 * @param manifoldObject The manifold object to convert
 * @param options Export options (optional)
 * @returns A Promise that resolves to a 3MF blob
 * @throws Error if the conversion fails
 */
export async function manifoldTo3MF(
  manifoldObject: ManifoldType, 
  options: Export3MFOptions = {}
): Promise<Blob> {
  try {
    // Get mesh data from the manifold object
    const mesh = manifoldObject.getMesh();
    
    if (!mesh.vertProperties || !mesh.triVerts) {
      throw new Error("Invalid mesh data for 3MF export");
    }

    // Extract vertex positions (first 3 components of each vertex)
    const vertices = mesh.numProp === 3 
      ? mesh.vertProperties 
      : new Float32Array(mesh.numVert * 3);
    
    if (mesh.numProp > 3) {
      for (let i = 0; i < mesh.numVert; ++i) {
        for (let j = 0; j < 3; ++j) {
          vertices[i * 3 + j] = mesh.vertProperties[i * mesh.numProp + j];
        }
      }
    }

    // Create 3MF data structure following ManifoldCAD example
    const to3mf: To3MF = {
      meshes: [{
        id: '1',
        vertices,
        indices: mesh.triVerts,
        name: options.filename || 'manifold-model'
      }],
      components: [],
      items: [{
        objectID: '1'
      }],
      precision: options.precision || 7,
      header: {
        unit: 'millimeter',
        title: 'Manifold Studio Model',
        description: 'Generated by Manifold Studio',
        application: 'Manifold Studio',
        ...options.header
      }
    };

    // Convert to 3MF XML format
    const model = to3dmodel(to3mf as any);

    // Create 3MF file structure (ZIP archive)
    const fileForRelThumbnail = new FileForRelThumbnail();
    fileForRelThumbnail.add3dModel('3D/3dmodel.model');

    const files: Zippable = {};
    files['3D/3dmodel.model'] = strToU8(model);
    files[fileForContentTypes.name] = strToU8(fileForContentTypes.content);
    files[fileForRelThumbnail.name] = strToU8(fileForRelThumbnail.content);

    // Create ZIP file
    const zipFile = zipSync(files);

    // Return as blob with correct MIME type
    return new Blob(
      [zipFile], 
      { type: 'application/vnd.ms-package.3dmanufacturing-3dmodel+xml' }
    );

  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown 3MF export error';
    throw new Error(`3MF export failed: ${errorMessage}`);
  }
}

/**
 * Export a manifold to 3MF format blob (convenience function)
 * @param model The manifold instance to export
 * @param options Export options (optional)
 * @returns A Blob containing the 3MF data
 * @throws Error if the model data is invalid
 */
export function exportTo3MF(model: ManifoldType, options?: Export3MFOptions): Promise<Blob> {
  return manifoldTo3MF(model, options);
}
