/**
 * Function Generator
 * 
 * Generates the final pipeline.js file with all compiled model functions.
 * This creates the structure shown in the V3 document.
 */

import type { CompiledFunction } from './model-compiler.js';

/**
 * Generate the complete pipeline.js code
 * 
 * @param compiledFunctions - Array of compiled function metadata
 * @returns Complete pipeline.js source code
 */
export function generatePipelineCode(compiledFunctions: CompiledFunction[]): string {
  const timestamp = new Date().toISOString();
  const modelCount = compiledFunctions.length;

  // Generate the main pipeline object
  const pipelineObject = generatePipelineObject(compiledFunctions, modelCount);
  
  // Generate all individual function definitions
  const functionDefinitions = compiledFunctions
    .map(func => func.functionCode)
    .join('\n\n');

  // Generate the complete file
  return `/**
 * Generated Pipeline Functions
 * 
 * This file is automatically generated by the V3 Pipeline Compiler.
 * Do not edit manually - changes will be overwritten.
 * 
 * Generated: ${timestamp}
 * Models: ${modelCount}
 */

${functionDefinitions}

${pipelineObject}

// Export the pipeline as default
export default pipeline;

// Also export as named export for compatibility
export { pipeline };
`;
}

/**
 * Generate the main pipeline object that implements ModelPipeline interface
 */
function generatePipelineObject(compiledFunctions: CompiledFunction[], modelCount: number): string {
  // Generate model list for getAvailableModels()
  const modelList = compiledFunctions.map(func => ({
    id: func.id,
    name: func.name,
    type: func.type
  }));

  // Generate switch cases for generateModel()
  const generateModelCases = compiledFunctions.map(func => 
    `    case "${func.id}":
      return await ${func.functionName}(params);`
  ).join('\n');

  // Generate config cases for getModelConfig()
  const configCases = compiledFunctions
    .filter(func => func.type === 'parametric' && func.config)
    .map(func => 
      `    case "${func.id}":
      return ${JSON.stringify(func.config, null, 6)};`
    ).join('\n');

  return `// Main pipeline object implementing ModelPipeline interface
const pipeline = {
  /**
   * Get list of all available models
   */
  getAvailableModels() {
    return ${JSON.stringify(modelList, null, 4)};
  },

  /**
   * Generate a model with the given parameters
   */
  async generateModel(modelId, params = {}) {
    switch (modelId) {
${generateModelCases}
      default:
        throw new Error(\`Unknown model: \${modelId}\`);
    }
  },

  /**
   * Get parameter configuration for a parametric model
   */
  getModelConfig(modelId) {
    switch (modelId) {
${configCases}
      default:
        return null;
    }
  },

  /**
   * Get metadata about the pipeline
   */
  getPipelineInfo() {
    return {
      version: "${Date.now()}",
      modelCount: ${modelCount},
      generatedAt: "${new Date().toISOString()}",
      models: this.getAvailableModels()
    };
  }
};`;
}

/**
 * Generate a safe JavaScript identifier from a model ID
 * 
 * @param modelId - Model ID to convert
 * @returns Safe JavaScript function name
 */
export function generateFunctionName(modelId: string): string {
  return `generate_${modelId.replace(/[\/\-\.]/g, '_')}`;
}

/**
 * Generate import statements for external dependencies
 * 
 * @param compiledFunctions - Array of compiled functions
 * @returns Import statements string
 */
export function generateImports(compiledFunctions: CompiledFunction[]): string {
  // For now, we'll handle imports within each function
  // In the future, we might want to optimize by hoisting common imports
  return `// Imports are handled within individual functions for now
// This allows for better isolation and cache busting`;
}

/**
 * Generate TypeScript type definitions for the pipeline
 * 
 * @param compiledFunctions - Array of compiled functions
 * @returns TypeScript definitions
 */
export function generateTypeDefinitions(compiledFunctions: CompiledFunction[]): string {
  const modelIds = compiledFunctions.map(f => `"${f.id}"`).join(' | ');
  
  return `// TypeScript definitions for the generated pipeline
export interface GeneratedPipeline {
  getAvailableModels(): Array<{
    id: ${modelIds};
    name: string;
    type: 'static' | 'parametric';
  }>;
  
  generateModel(modelId: ${modelIds}, params?: any): Promise<any>;
  getModelConfig(modelId: ${modelIds}): any;
  getPipelineInfo(): {
    version: string;
    modelCount: number;
    generatedAt: string;
    models: any[];
  };
}`;
}

/**
 * Validate that all compiled functions are valid
 * 
 * @param compiledFunctions - Array of compiled functions to validate
 * @returns Validation result with any errors
 */
export function validateCompiledFunctions(compiledFunctions: CompiledFunction[]): {
  isValid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  // Check for duplicate IDs
  const ids = compiledFunctions.map(f => f.id);
  const duplicateIds = ids.filter((id, index) => ids.indexOf(id) !== index);
  if (duplicateIds.length > 0) {
    errors.push(`Duplicate model IDs found: ${duplicateIds.join(', ')}`);
  }

  // Check for empty function names
  const emptyNames = compiledFunctions.filter(f => !f.functionName);
  if (emptyNames.length > 0) {
    errors.push(`Functions with empty names: ${emptyNames.map(f => f.id).join(', ')}`);
  }

  // Check for empty function code
  const emptyCode = compiledFunctions.filter(f => !f.functionCode);
  if (emptyCode.length > 0) {
    errors.push(`Functions with empty code: ${emptyCode.map(f => f.id).join(', ')}`);
  }

  return {
    isValid: errors.length === 0,
    errors
  };
}
