/**
 * V3 Model Service
 * 
 * Pipeline-based model service for V3 architecture.
 * Integrates pipeline loading with UI state management.
 */

import type {
  IModelService,
  ModelLoadResult,
  ModelConfig,
  ProgressCallback
} from '../types/service.js';
import type { ModelPipeline } from '../types/pipeline.js';
import { createPipelineLoader } from '../core/pipeline-loader.js';
import { UIStateManager } from '../state/ui-state.js';
import { getExportService } from './index.js';

/**
 * V3 Model Service Implementation
 * 
 * This replaces the complex V1/V2 model services with a simple pipeline-based approach.
 * Instead of dynamic imports and complex HMR, we just reload the entire pipeline.
 */
export class V3ModelService implements IModelService {
  private pipelineLoader: any;
  private uiStateManager = new UIStateManager();
  private isInitialized = false;

  constructor(pipelinePath?: string) {
    this.pipelineLoader = createPipelineLoader(pipelinePath);
    this.setupPipelineReloadHandler();
  }

  /**
   * Initialize the service
   */
  async initialize(): Promise<boolean> {
    if (this.isInitialized) {
      return true;
    }

    console.log('🚀 Initializing V3 Model Service...');

    try {
      // Initialize pipeline loader with auto-check
      const success = await this.pipelineLoader.initialize(true);
      
      this.isInitialized = true;
      console.log('✅ V3 Model Service initialized');
      
      return success;
    } catch (error) {
      console.error('❌ Failed to initialize V3 Model Service:', error);
      return false;
    }
  }

  /**
   * Load a model using the current pipeline
   */
  async loadModel(
    modelId: string, 
    params: any = {}, 
    onProgress?: ProgressCallback
  ): Promise<ModelLoadResult> {
    console.log(`🔨 Loading model: ${modelId}`, params);

    onProgress?.(0, 'Getting pipeline...');

    const pipeline = this.pipelineLoader.getPipeline();
    if (!pipeline) {
      throw new Error('Pipeline not available. Make sure the pipeline build server is running.');
    }

    onProgress?.(25, 'Checking model availability...');

    // Verify model exists
    const availableModels = pipeline.getAvailableModels();
    const modelConfig = availableModels.find(m => m.id === modelId);
    
    if (!modelConfig) {
      throw new Error(`Model not found: ${modelId}. Available models: ${availableModels.map(m => m.id).join(', ')}`);
    }

    onProgress?.(50, 'Generating model...');

    try {
      // Generate the model using the pipeline
      const model = await pipeline.generateModel(modelId, params);

      onProgress?.(75, 'Generating exports...');

      // Generate exports (GLB and OBJ)
      const exportService = getExportService();
      const objResult = await exportService.exportToOBJ(model, `${modelId}.obj`);
      const glbResult = await exportService.exportToGLB(model, `${modelId}.glb`);

      // Get parametric config if available
      const parametricConfig = pipeline.getModelConfig(modelId);

      onProgress?.(100, 'Complete');

      // Update UI state
      this.uiStateManager.selectModel(modelId, params);

      const result: ModelLoadResult = {
        model,
        metadata: {
          name: modelConfig.name,
          description: `Generated by V3 pipeline`
        },
        isParametric: modelConfig.type === 'parametric',
        config: parametricConfig || undefined,
        exports: {
          objUrl: objResult.url,
          glbUrl: glbResult.url
        }
      };

      console.log(`✅ Model loaded: ${modelId} (${modelConfig.type})`);
      return result;

    } catch (error) {
      console.error(`❌ Failed to generate model ${modelId}:`, error);
      throw new Error(`Model generation failed: ${error instanceof Error ? error.message : error}`);
    }
  }

  /**
   * Get available models from the current pipeline
   */
  getAvailableModels(): { id: string; name: string; type: 'static' | 'parametric' }[] {
    const pipeline = this.pipelineLoader.getPipeline();
    if (!pipeline) {
      console.warn('⚠️ Pipeline not available, returning empty model list');
      return [];
    }

    const models = pipeline.getAvailableModels();
    // Convert to the format expected by the interface
    return models.map((model: any) => ({
      id: model.id,
      name: model.name || model.id,
      type: model.type || (model.config ? 'parametric' : 'static')
    }));
  }

  /**
   * Check if a model is parametric
   */
  isParametric(modelId: string): boolean {
    const models = this.getAvailableModels();
    const model = models.find(m => m.id === modelId);
    return model?.type === 'parametric' || false;
  }

  /**
   * Get parameter configuration for a parametric model
   */
  getParameterConfig(modelId: string): any {
    const pipeline = this.pipelineLoader.getPipeline();
    if (!pipeline) {
      return null;
    }

    return pipeline.getModelConfig(modelId);
  }

  /**
   * Set the pipeline to use for model operations
   * (This method is for interface compatibility, but V3 manages pipeline automatically)
   */
  setPipeline(pipeline: ModelPipeline): void {
    console.warn('⚠️ setPipeline() called on V3ModelService. V3 manages pipeline automatically.');
    // In V3, we don't manually set pipelines - they're loaded automatically
  }

  /**
   * Get UI state manager
   */
  getUIStateManager(): UIStateManager {
    return this.uiStateManager;
  }

  /**
   * Get current UI state
   */
  getUIState() {
    return this.uiStateManager.getState();
  }

  /**
   * Check for pipeline updates manually
   */
  async checkForUpdates(): Promise<boolean> {
    return await this.pipelineLoader.checkForUpdates();
  }

  /**
   * Get pipeline info
   */
  getPipelineInfo() {
    const pipeline = this.pipelineLoader.getPipeline();
    return pipeline?.getPipelineInfo?.() || null;
  }

  /**
   * Setup pipeline reload handler
   */
  private setupPipelineReloadHandler(): void {
    // This will be called whenever the pipeline is reloaded
    // We can use this to trigger UI updates, preserve state, etc.
    
    // For now, we'll handle this through the auto-check mechanism
    // In a full implementation, this would integrate with the UI framework
    console.log('🔄 Pipeline reload handler set up');
  }

  /**
   * Add listener for pipeline changes
   */
  onPipelineChange(callback: () => void): () => void {
    // Start auto-check if not already running
    if (!this.isInitialized) {
      this.initialize();
    }

    // For now, we'll use a simple polling approach
    // In a full implementation, this would be event-driven
    const interval = setInterval(async () => {
      try {
        const wasUpdated = await this.pipelineLoader.checkForUpdates();
        if (wasUpdated) {
          // Handle pipeline reload
          const pipelineInfo = this.getPipelineInfo();
          this.uiStateManager.handlePipelineReload(pipelineInfo?.version);
          
          // Notify callback
          callback();
        }
      } catch (error) {
        console.error('Pipeline change check error:', error);
      }
    }, 1000);

    // Return cleanup function
    return () => {
      clearInterval(interval);
    };
  }

  /**
   * Refresh available models (V3 reloads pipeline)
   */
  refreshAvailableModels(): void {
    // In V3, this means reloading the pipeline
    this.pipelineLoader.checkForUpdates();
  }

  /**
   * Get cached model (V3 doesn't cache models, generates on demand)
   */
  getCachedModel(modelId: string): any | null {
    // V3 doesn't cache models - they're generated on demand from pipeline
    return null;
  }

  /**
   * Clear cache (no-op for V3)
   */
  clearCache(): void {
    // V3 doesn't cache models, so this is a no-op
    console.log('V3 Model Service: clearCache() called (no-op)');
  }

  /**
   * Cleanup resources
   */
  destroy(): void {
    this.pipelineLoader.destroy();
    console.log('🧹 V3 Model Service destroyed');
  }
}

/**
 * Factory function to create V3 model service
 */
export function createV3ModelService(pipelinePath?: string): V3ModelService {
  return new V3ModelService(pipelinePath);
}
