/**
 * V3 Model Service
 * 
 * Pipeline-based model service for V3 architecture.
 * Integrates pipeline loading with UI state management.
 */

import type {
  IModelService,
  ModelLoadResult,
  ModelConfig,
  ProgressCallback
} from '../types/service.js';
import type { ModelPipeline } from '../types/pipeline.js';
import { createPipelineLoader } from '../core/pipeline-loader.js';
import { UIStateManager } from '../state/ui-state.js';
import { getExportService } from './index.js';

/**
 * V3 Model Service Implementation
 * 
 * This replaces the complex V1/V2 model services with a simple pipeline-based approach.
 * Instead of dynamic imports and complex HMR, we just reload the entire pipeline.
 */
export class V3ModelService implements IModelService {
  private pipelineLoader: any;
  private uiStateManager = new UIStateManager();
  private isInitialized = false;

  constructor(pipelinePath?: string) {
    this.pipelineLoader = createPipelineLoader(pipelinePath);
    this.setupPipelineReloadHandler();
  }

  /**
   * Initialize the service
   */
  async initialize(): Promise<boolean> {
    if (this.isInitialized) {
      return true;
    }

    console.log('🚀 Initializing V3 Model Service...');

    try {
      // Initialize pipeline loader without auto-check (using custom HMR instead)
      const success = await this.pipelineLoader.initialize(false);
      
      this.isInitialized = true;
      console.log('✅ V3 Model Service initialized');
      
      return success;
    } catch (error) {
      console.error('❌ Failed to initialize V3 Model Service:', error);
      return false;
    }
  }

  /**
   * Load a model using the current pipeline
   */
  async loadModel(
    modelId: string, 
    params: any = {}, 
    onProgress?: ProgressCallback
  ): Promise<ModelLoadResult> {
    console.log(`🔨 Loading model: ${modelId}`, params);

    onProgress?.(0, 'Getting pipeline...');

    const pipeline = this.pipelineLoader.getPipeline();
    if (!pipeline) {
      throw new Error('Pipeline not available. Make sure the pipeline build server is running.');
    }

    onProgress?.(25, 'Checking model availability...');

    // Verify model exists
    const availableModels = pipeline.getAvailableModels();
    const modelConfig = availableModels.find(m => m.id === modelId);

    if (!modelConfig) {
      throw new Error(`Model not found: ${modelId}. Available models: ${availableModels.map(m => m.id).join(', ')}`);
    }

    onProgress?.(50, 'Generating model...');

    try {
      // Generate the model using the pipeline
      const model = await pipeline.generateModel(modelId, params);

      onProgress?.(75, 'Generating exports...');

      // Generate exports (GLB and OBJ)
      const exportService = getExportService();
      const objResult = await exportService.exportToOBJ(model, `${modelId}.obj`);
      const glbResult = await exportService.exportToGLB(model, `${modelId}.glb`);

      // Get parametric config if available
      const parametricConfig = pipeline.getModelConfig(modelId);

      onProgress?.(100, 'Complete');

      // Update UI state
      this.uiStateManager.selectModel(modelId, params);

      // Get full metadata including description from manifest
      let description = 'Generated by V3 pipeline'; // fallback

      // Try to get description from manifest data first
      const manifestData = (pipeline as any).manifestData;
      console.log(`🔍 DEBUG V3ModelService: manifestData available:`, !!manifestData);
      console.log(`🔍 DEBUG V3ModelService: manifestData.models:`, manifestData?.models?.length);

      if (manifestData && manifestData.models) {
        const manifestModel = manifestData.models.find((m: any) => m.id === modelId);
        console.log(`🔍 DEBUG V3ModelService: Found manifest model for ${modelId}:`, manifestModel);
        if (manifestModel && manifestModel.description) {
          description = manifestModel.description;
          console.log(`🔍 DEBUG V3ModelService: Using manifest description: "${description}"`);
        }
      }

      // Fallback to config-based descriptions if manifest doesn't have it
      if (description === 'Generated by V3 pipeline') {
        if (modelConfig.type === 'parametric') {
          // For parametric models, get description from the full config
          const fullConfig = pipeline.getModelConfig(modelId);
          description = fullConfig?.description || `Parametric model: ${modelConfig.name}`;
        } else {
          // For static models, fallback to generic description
          description = `Static model: ${modelConfig.name}`;
        }
      }

      const metadata = {
        name: modelConfig.name,
        description: description
      };

      const result: ModelLoadResult = {
        model,
        metadata,
        isParametric: modelConfig.type === 'parametric',
        config: parametricConfig || undefined,
        exports: {
          objUrl: objResult.url,
          glbUrl: glbResult.url
        }
      };

      console.log(`✅ Model loaded: ${modelId} (${modelConfig.type})`);
      return result;

    } catch (error) {
      console.error(`❌ Failed to generate model ${modelId}:`, error);
      throw new Error(`Model generation failed: ${error instanceof Error ? error.message : error}`);
    }
  }

  /**
   * Get available models from the current pipeline
   */
  getAvailableModels(): { id: string; name: string; type: 'static' | 'parametric' }[] {
    const pipeline = this.pipelineLoader.getPipeline();
    if (!pipeline) {
      console.warn('⚠️ Pipeline not available, returning empty model list');
      return [];
    }

    const models = pipeline.getAvailableModels();
    // Convert to the format expected by the interface
    return models.map((model: any) => ({
      id: model.id,
      name: model.name || model.id,
      type: model.type || (model.config ? 'parametric' : 'static')
    }));
  }

  /**
   * Check if a model is parametric
   */
  isParametric(modelId: string): boolean {
    const models = this.getAvailableModels();
    const model = models.find(m => m.id === modelId);
    return model?.type === 'parametric' || false;
  }

  /**
   * Get parameter configuration for a parametric model
   */
  getParameterConfig(modelId: string): any {
    const pipeline = this.pipelineLoader.getPipeline();
    if (!pipeline) {
      return null;
    }

    return pipeline.getModelConfig(modelId);
  }

  /**
   * Set the pipeline to use for model operations
   * (This method is for interface compatibility, but V3 manages pipeline automatically)
   */
  setPipeline(_pipeline: ModelPipeline): void {
    // In V3, we don't manually set pipelines - they're loaded automatically
  }

  /**
   * Get UI state manager
   */
  getUIStateManager(): UIStateManager {
    return this.uiStateManager;
  }

  /**
   * Get current UI state
   */
  getUIState() {
    return this.uiStateManager.getState();
  }



  /**
   * Get pipeline info
   */
  getPipelineInfo() {
    const pipeline = this.pipelineLoader.getPipeline();
    return pipeline?.getPipelineInfo?.() || null;
  }

  /**
   * Setup pipeline reload handler
   */
  private setupPipelineReloadHandler(): void {
    // This will be called whenever the pipeline is reloaded
    // We can use this to trigger UI updates, preserve state, etc.
    
    // For now, we'll handle this through the auto-check mechanism
    // In a full implementation, this would integrate with the UI framework
    console.log('🔄 Pipeline reload handler set up');
  }

  /**
   * Add listener for pipeline changes
   * Note: In V3, pipeline changes are handled by custom HMR events
   */
  onPipelineChange(_callback: () => void): () => void {
    // Return no-op cleanup function
    return () => {};
  }

  /**
   * Refresh available models (V3 reloads pipeline)
   */
  refreshAvailableModels(): void {
    // In V3, pipeline refresh is handled by HMR events
  }

  /**
   * Force reload the pipeline module (for HMR)
   */
  async reloadPipeline(): Promise<void> {
    try {
      await this.pipelineLoader.reloadPipeline();
    } catch (error) {
      console.error('Pipeline reload failed:', error);
      throw error;
    }
  }

  /**
   * Get cached model (V3 doesn't cache models, generates on demand)
   */
  getCachedModel(_modelId: string): any | null {
    // V3 doesn't cache models - they're generated on demand from pipeline
    return null;
  }

  /**
   * Clear cache (no-op for V3)
   */
  clearCache(): void {
    // V3 doesn't cache models, so this is a no-op
  }

  /**
   * Cleanup resources
   */
  destroy(): void {
    this.pipelineLoader.destroy();
    console.log('🧹 V3 Model Service destroyed');
  }
}

/**
 * Factory function to create V3 model service
 */
export function createV3ModelService(pipelinePath?: string): V3ModelService {
  return new V3ModelService(pipelinePath);
}
