import type { ModelFile } from './types.js';

/**
 * Generates a pipeline entry file with static imports for all discovered models
 * This replaces the hardcoded pipeline-entry.ts that users currently maintain
 */
export function generatePipelineEntry(models: ModelFile[]): string {
  if (models.length === 0) {
    return generateEmptyPipelineEntry();
  }
  
  // Generate import statements
  const imports = models
    .map(model => `import * as ${model.exportName} from '${model.importPath}';`)
    .join('\n');
    
  // Generate model definitions array
  const modelDefinitions = models
    .map(model => `  { id: '${model.id}', module: ${model.exportName} }`)
    .join(',\n');
    
  return `// Auto-generated pipeline entry
// This file is generated by manifold-dev and should not be edited manually
// Generated at: ${new Date().toISOString()}

${imports}

export const modelDefinitions = [
${modelDefinitions}
];

// Export individual models for compatibility
${models.map(model => `export { ${model.exportName} };`).join('\n')}

// Pipeline interface (matches existing V3 structure)
export function createPipeline() {
  return {
    models: modelDefinitions,
    getModel: (id: string) => {
      const model = modelDefinitions.find(m => m.id === id);
      return model?.module;
    }
  };
}

// Generate manifest data (matches V3 structure)
export const manifestData = {
  version: Date.now().toString(),
  generatedAt: new Date().toISOString(),
  models: modelDefinitions.map(model => {
    // For now, we'll generate basic metadata
    // TODO: Extract actual parameter schemas and descriptions from model modules
    return {
      id: model.id,
      name: model.id.replace(/^components\//, '').replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()),
      type: 'static', // Default to static for now
      description: \`Model: \${model.id}\`
    };
  })
};

// Default export for compatibility
export default createPipeline;
`;
}

/**
 * Generates an empty pipeline entry when no models are found
 */
function generateEmptyPipelineEntry(): string {
  return `// Auto-generated pipeline entry
// This file is generated by manifold-dev and should not be edited manually
// Generated at: ${new Date().toISOString()}
// No models found in project

export const modelDefinitions = [];

export function createPipeline() {
  return {
    models: [],
    getModel: (id: string) => undefined
  };
}

export default createPipeline;
`;
}

/**
 * Validates the generated pipeline entry by checking for syntax errors
 */
export function validatePipelineEntry(pipelineCode: string): { valid: boolean; error?: string } {
  try {
    // Basic syntax validation - try to parse as TypeScript/JavaScript
    // This is a simple check, more sophisticated validation could be added
    if (!pipelineCode.includes('export const modelDefinitions')) {
      return { valid: false, error: 'Missing modelDefinitions export' };
    }

    if (!pipelineCode.includes('export function createPipeline')) {
      return { valid: false, error: 'Missing createPipeline export' };
    }

    if (!pipelineCode.includes('export const manifestData')) {
      return { valid: false, error: 'Missing manifestData export' };
    }

    return { valid: true };
  } catch (error) {
    return {
      valid: false,
      error: error instanceof Error ? error.message : 'Unknown validation error'
    };
  }
}

/**
 * Generates manifest.json content from discovered models
 */
export function generateManifest(models: ModelFile[]): string {
  const manifest = {
    version: Date.now().toString(),
    generatedAt: new Date().toISOString(),
    models: models.map(model => {
      // For now, we'll generate basic metadata
      // TODO: Extract actual parameter schemas and descriptions from model modules
      return {
        id: model.id,
        name: model.id.replace(/^components\//, '').replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase()),
        type: 'static', // Default to static for now
        description: `Model: ${model.id}`
      };
    })
  };

  return JSON.stringify(manifest, null, 2);
}
