import type { ModelFile } from './types.js';

/**
 * Generates a pipeline entry file with static imports for all discovered models
 * This replaces the hardcoded pipeline-entry.ts that users currently maintain
 */
export function generatePipelineEntry(models: ModelFile[]): string {
  if (models.length === 0) {
    return generateEmptyPipelineEntry();
  }
  
  // Generate import statements
  const imports = models
    .map(model => `import * as ${model.exportName} from '${model.importPath}';`)
    .join('\n');
    
  // Generate model definitions array
  const modelDefinitions = models
    .map(model => `  { id: '${model.id}', module: ${model.exportName} }`)
    .join(',\n');
    
  return `// Auto-generated pipeline entry
// This file is generated by manifold-dev and should not be edited manually
// Generated at: ${new Date().toISOString()}

${imports}

export const modelDefinitions = [
${modelDefinitions}
];

// Export individual models for compatibility
${models.map(model => `export { ${model.exportName} };`).join('\n')}

// ============================================================================
// PIPELINE RUNTIME - Reusable logic (auto-generated, do not edit manually)
// ============================================================================

// Type definitions
interface ParametricConfig {
  name: string;
  description?: string;
  parameters: Record<string, { value: any; min?: any; max?: any; }>;
  generateModel: (params: any) => any;
}

interface ParametricModel {
  id: string;
  name: string;
  type: 'parametric';
  config: ParametricConfig;
  defaultParams: Record<string, any>;
}

interface StaticModel {
  id: string;
  name: string;
  type: 'static';
  createFunction: () => any;
  metadata?: any;
}

type ProcessedModel = ParametricModel | StaticModel;

// Helper functions
function isParametricConfig(obj: any): obj is ParametricConfig {
  return (
    obj &&
    typeof obj === 'object' &&
    'parameters' in obj &&
    'generateModel' in obj &&
    typeof obj.generateModel === 'function'
  );
}

function extractDefaultParams(config: ParametricConfig): Record<string, any> {
  const defaultParams: Record<string, any> = {};
  for (const [key, paramConfig] of Object.entries(config.parameters)) {
    defaultParams[key] = paramConfig.value;
  }
  return defaultParams;
}

// Process models using proven working logic
const processedModels: ProcessedModel[] = modelDefinitions.map(({ id, module }) => {
  const defaultExport = (module as any).default || module;

  if (isParametricConfig(defaultExport)) {
    return {
      id,
      name: defaultExport.name || id,
      type: 'parametric' as const,
      config: defaultExport,
      defaultParams: extractDefaultParams(defaultExport)
    } as ParametricModel;
  } else if (typeof defaultExport === 'function') {
    const metadata = module.modelMetadata || {};
    return {
      id,
      name: metadata.name || id,
      type: 'static' as const,
      createFunction: defaultExport,
      metadata: metadata
    } as StaticModel;
  } else {
    throw new Error(\`Invalid model export in \${id}\`);
  }
});

// Create pipeline using proven working logic
const pipeline = {
  getAvailableModels() {
    return processedModels.map(model => ({
      id: model.id,
      name: model.name,
      type: model.type
    }));
  },

  async generateModel(modelId: string, params: any = {}) {
    const model = processedModels.find(m => m.id === modelId);
    if (!model) {
      throw new Error(\`Unknown model: \${modelId}\`);
    }

    if (model.type === 'parametric') {
      const parametricModel = model as ParametricModel;
      const finalParams = { ...parametricModel.defaultParams, ...params };
      return parametricModel.config.generateModel(finalParams);
    } else {
      const staticModel = model as StaticModel;
      return staticModel.createFunction();
    }
  },

  getModelConfig(modelId: string) {
    const model = processedModels.find(m => m.id === modelId);
    if (!model || model.type !== 'parametric') {
      return null;
    }
    return (model as ParametricModel).config;
  }
};

// Legacy createPipeline function for compatibility
export function createPipeline() {
  return {
    models: modelDefinitions,
    getModel: (id: string) => {
      const model = modelDefinitions.find(m => m.id === id);
      return model?.module;
    }
  };
}

// Generate manifest data
export const manifestData = {
  version: Date.now().toString(),
  generatedAt: new Date().toISOString(),
  models: modelDefinitions.map(model => ({
    id: model.id,
    name: model.id.replace(/^components\\//, '').replace(/[-_]/g, ' ').split(' ').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' '),
    type: 'static',
    description: \`Model: \${model.id}\`
  }))
};

// Export the pipeline as default (ModelPipeline interface)
export default pipeline;
`;
}

/**
 * Generates an empty pipeline entry when no models are found
 */
function generateEmptyPipelineEntry(): string {
  return `// Auto-generated pipeline entry
// This file is generated by manifold-dev and should not be edited manually
// Generated at: ${new Date().toISOString()}
// No models found in project

export const modelDefinitions = [];

export function createPipeline() {
  return {
    models: [],
    getModel: (id: string) => undefined
  };
}

export default createPipeline;
`;
}

/**
 * Validates the generated pipeline entry by checking for syntax errors
 */
export function validatePipelineEntry(pipelineCode: string): { valid: boolean; error?: string } {
  try {
    // Basic syntax validation - try to parse as TypeScript/JavaScript
    // This is a simple check, more sophisticated validation could be added
    if (!pipelineCode.includes('export const modelDefinitions')) {
      return { valid: false, error: 'Missing modelDefinitions export' };
    }

    if (!pipelineCode.includes('export function createPipeline')) {
      return { valid: false, error: 'Missing createPipeline export' };
    }

    if (!pipelineCode.includes('export const manifestData')) {
      return { valid: false, error: 'Missing manifestData export' };
    }

    return { valid: true };
  } catch (error) {
    return {
      valid: false,
      error: error instanceof Error ? error.message : 'Unknown validation error'
    };
  }
}

/**
 * Generates manifest.json content from discovered models
 */
export function generateManifest(models: ModelFile[]): string {
  const manifest = {
    version: Date.now().toString(),
    generatedAt: new Date().toISOString(),
    models: models.map(model => {
      // For now, we'll generate basic metadata
      // TODO: Extract actual parameter schemas and descriptions from model modules
      return {
        id: model.id,
        name: model.id.replace(/^components\//, '').replace(/[-_]/g, ' ').split(' ').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' '),
        type: 'static', // Default to static for now
        description: `Model: ${model.id}`
      };
    })
  };

  return JSON.stringify(manifest, null, 2);
}
