/**
 * Metadata Extraction Test
 * 
 * Tests to verify that static model metadata extraction works correctly
 * in the V3 pipeline system.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { existsSync } from 'fs';
import { readFile } from 'fs/promises';

describe('V3 Metadata Extraction', () => {
  describe('Pipeline Compilation', () => {
    it('should compile pipeline with manifestData export', async () => {
      // Skip if pipeline not built yet
      if (!existsSync('./temp/pipeline.js')) {
        console.log('⏭️ Skipping pipeline compilation test - pipeline not built');
        return;
      }

      // Read the compiled pipeline
      const pipelineContent = await readFile('./temp/pipeline.js', 'utf-8');

      // Should export manifestData
      expect(pipelineContent).toContain('export { manifestData }');
      expect(pipelineContent).toContain('export default pipeline');
    });

    it('should generate manifest with correct static model descriptions', async () => {
      // Skip if manifest not generated yet
      if (!existsSync('./temp/manifest.json')) {
        console.log('⏭️ Skipping manifest test - manifest not generated');
        return;
      }

      // Read and parse manifest
      const manifestContent = await readFile('./temp/manifest.json', 'utf-8');
      const manifest = JSON.parse(manifestContent);

      // Should have models array
      expect(Array.isArray(manifest.models)).toBe(true);
      expect(manifest.models.length).toBeGreaterThan(0);

      // Find the simple-cube static model
      const simpleCube = manifest.models.find((m: any) => m.id === 'components/simple-cube');
      expect(simpleCube).toBeDefined();
      expect(simpleCube.type).toBe('static');

      // Should have the correct description from metadata, not generic fallback
      expect(simpleCube.description).toBe('A basic 5x5x5 cube for testing');
      expect(simpleCube.description).not.toBe('Static model: Simple Cube');
      expect(simpleCube.description).not.toBe('Generated by V3 pipeline');
    });

    it('should handle parametric models correctly', async () => {
      // Skip if manifest not generated yet
      if (!existsSync('./temp/manifest.json')) {
        console.log('⏭️ Skipping parametric model test - manifest not generated');
        return;
      }

      const manifestContent = await readFile('./temp/manifest.json', 'utf-8');
      const manifest = JSON.parse(manifestContent);

      // Find a parametric model
      const parametricModel = manifest.models.find((m: any) => m.type === 'parametric');
      expect(parametricModel).toBeDefined();

      // Should have config with parameters
      expect(parametricModel.config).toBeDefined();
      expect(parametricModel.config.parameters).toBeDefined();

      // Should have description (either from config or fallback)
      expect(typeof parametricModel.description === 'string' ||
             typeof parametricModel.config.description === 'string').toBe(true);
    });
  });

  describe('Pipeline Loader Integration', () => {
    it('should load pipeline with manifestData attached', async () => {
      // Skip if pipeline not built yet
      if (!existsSync('./temp/pipeline.js')) {
        console.log('⏭️ Skipping pipeline loader test - pipeline not built');
        return;
      }

      try {
        // Dynamic import the compiled pipeline
        const cacheBuster = `?t=${Date.now()}`;
        const module = await import(`./temp/pipeline.js${cacheBuster}`);

        // Should have pipeline export
        const pipeline = module.default || module.pipeline;
        expect(pipeline).toBeDefined();
        expect(typeof pipeline.getAvailableModels).toBe('function');

        // Should have manifestData export
        expect(module.manifestData).toBeDefined();
        expect(Array.isArray(module.manifestData.models)).toBe(true);

        // ManifestData should contain the correct static model description
        const simpleCube = module.manifestData.models.find((m: any) => m.id === 'components/simple-cube');
        expect(simpleCube).toBeDefined();
        expect(simpleCube.description).toBe('A basic 5x5x5 cube for testing');
      } catch (error) {
        console.log('⏭️ Skipping pipeline loader test - dynamic import not supported in test environment');
      }
    });
  });

  describe('Model Metadata Structure', () => {
    it('should validate static model metadata exports', async () => {
      // Import the static model directly
      const simpleCubeModule = await import('../components/simple-cube.ts');
      
      // Should have modelMetadata export
      expect(simpleCubeModule.modelMetadata).toBeDefined();
      expect(typeof simpleCubeModule.modelMetadata.name).toBe('string');
      expect(typeof simpleCubeModule.modelMetadata.description).toBe('string');
      
      // Should match what we expect in the manifest
      expect(simpleCubeModule.modelMetadata.description).toBe('A basic 5x5x5 cube for testing');
    });

    it('should validate parametric model config exports', async () => {
      // Import a parametric model
      const wheelModule = await import('../components/wheel.ts');

      // Should have default export with config
      expect(wheelModule.default).toBeDefined();
      expect(wheelModule.default.parameters).toBeDefined();

      // Should have description in config
      expect(typeof wheelModule.default.description).toBe('string');
      expect(wheelModule.default.description).toBe('A customizable wheel with tire and rim - now with V3 live updates!');
    });
  });

  describe('Metadata Extraction Edge Cases', () => {
    it('should handle missing metadata gracefully', () => {
      // This test validates that the optional chaining approach works
      // when metadata is undefined
      const testStaticModel = { id: 'test', metadata: undefined };
      const description = testStaticModel?.metadata?.description || `Static model: test`;
      
      expect(description).toBe('Static model: test');
    });

    it('should handle partial metadata gracefully', () => {
      // Test with metadata object but no description
      const testStaticModel = { id: 'test', metadata: { name: 'Test' } };
      const description = testStaticModel?.metadata?.description || `Static model: ${testStaticModel.metadata.name}`;
      
      expect(description).toBe('Static model: Test');
    });

    it('should prioritize metadata description over fallbacks', () => {
      // Test with complete metadata
      const testStaticModel = { 
        id: 'test', 
        metadata: { 
          name: 'Test Model',
          description: 'Custom description from metadata'
        } 
      };
      const description = testStaticModel?.metadata?.description || `Static model: ${testStaticModel.metadata.name}`;
      
      expect(description).toBe('Custom description from metadata');
    });
  });
});
